### ISSUE TITLE
Missing additional links in Readme files

### ISSUE THREAD

**Issue by mihai-burduselu** [microsoft-dx/advanced-csharp#1]
After creating new blog posts and repositories in microsoft-dx, we must update the Readme files with some links to these new resources.
For that, we must replace "this blog post (coming soon :sunglasses:) " with a link to the new blog-post.

/AsynchronousProgramming/Modern/Readme.md

![blog-post-async](https://cloud.githubusercontent.com/assets/16403502/17662100/e555bfb0-62eb-11e6-8259-05245b1d56e5.png)

/Delegates/Readme,md

![delegates](https://cloud.githubusercontent.com/assets/16403502/17662276/0c9c354e-62ed-11e6-8087-9908073605e6.png)

**Comment by laurentiustamate94** [comment]
Merged.
